FIx/Feat - Inclusão do campo busca e resolução de dois débitos técnicos
MateusOliveira991/koru_modulo4_app_flutter pull request #15
Opened 2024-05-12 02:37 UTC by marcotuliosr

Fix: Resolução de 2 débitos técnicos, campo em branco ao arrastar a tela / click estava vazio ao selecionar clicando no título

Feat: Criei a função para busca do campo Search de acordo com filme na lista, caso contrário ausência será exibida uma mensagem com título indisponível.

Por gentileza revisar se possível rodando a branch, para evitar bugs ou falhas nessa etapa final

2024-05-12 13:48 UTC, waxxp requested changes
Marco, quando pesquisa o filme no campo de busca, o carrosel de lista popular fica assim. No lista completa ele filtra e realmente só traz o filme buscado, mas esse carrossel me incomodou um pouco. Tem algum outro jeito de fazer isso em que o retorno seja um pouco mais agradável esteticamente? 

![image](https://github.com/MateusOliveira991/koru_modulo4_app_flutter/assets/86086432/c97f6bd2-0ad7-4c0b-a69b-1c33b04a6c34)


Outro ponto é que a lista de filmes mais populares filtra os filmes com o rotten tomates > 85. Quando o usuário faz a busca por um filme que a priori não ta na lista dos mais populares, tipo Pom Poko que tem o rotten tomates de 78, o título é puxado pro carrossel: 
![image](https://github.com/MateusOliveira991/koru_modulo4_app_flutter/assets/86086432/59566027-79b8-4665-8808-cea60fb4d12b)

2024-05-13 02:18 UTC, waxxp approved these changes

2024-05-13 10:49 UTC, Hevelise-Liz approved these changes

2024-05-13 10:58 UTC, lacatye approved these changes

2024-05-13 11:19 UTC, merged